apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
     project: roboshop
     tier: app
     component: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"

---

apiVersion: v1
kind: Secret
metadata:
  name: payment
  labels:
     project: roboshop
     tier: app
     component: payment 
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  #DEPLOYMENT LABELS
  labels:
     project: roboshop
     tier: app
     component: payment
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
       project: roboshop
       tier: app
       component: payment
  # This is pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: app
        component: payment
    spec:
      containers:
      - name: payment
        image: venkattholeti/payment:v1
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment

    #kubectl get pods -n roboshop (to see pods created under roboshop namespace)

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
     project: roboshop
     tier: app
     component: payment
spec:
  selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
     project: roboshop
     tier: app
     component: payment
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
