apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  #DEPLOYMENT LABELS
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
spec:
  replicas: 0
  #THESE ARE THE LABELS REPLICASET USES TO CREATE POD REPLICAS, THIS SHOULD MATCH POD TEMPLATE LABELS
  selector:
   matchLabels:
    project: roboshop
    tier: database
    component: rabbitmq
#THIS IS POD DEFINITION
  template:
    metadata:
     labels:
      project: roboshop
      tier: database
      component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          envFrom:
          - configMapRef:
             name: rabbitmq

    #kubectl get pods -n roboshop (to see pods created under roboshop namespace)

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
     project: roboshop
     tier: database
     component: rabbitmq
spec:
  selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
     project: roboshop
     tier: database
     component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port
