apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  #DEPLOYMENT LABELS
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  replicas: 1
  #THESE ARE THE LABELS REPLICASET USES TO CREATE POD REPLICAS, THIS SHOULD MATCH POD TEMPLATE LABELS
  selector:
   matchLabels:
    project: roboshop
    tier: database
    component: mongodb
#THIS IS POD DEFINITION
  template:
    metadata:
     labels:
     project: roboshop
     tier: database
     component: mongodb
    spec:
      containers:
        - name: nginx
          image: venkattholeti/mongodb:v1

    #kubectl get pods -n roboshop (to see pods created under roboshop namespace)

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
     project: roboshop
     tier: database
     component: mongodb
spec:
  selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
     project: roboshop
     tier: database
     component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port
