apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    project: roboshop
    tier: database
    component: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ==" 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  #DEPLOYMENT LABELS
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  replicas: 1
  #THESE ARE THE LABELS REPLICASET USES TO CREATE POD REPLICAS, THIS SHOULD MATCH POD TEMPLATE LABELS
  selector:
   matchLabels:
    project: roboshop
    tier: database
    component: mysql
#THIS IS POD DEFINITION
  template:
    metadata:
     labels:
      project: roboshop
      tier: database
      component: mysql
    spec:
      containers:
        - name: mysql
          image: venkattholeti/mysql:v1
          envFrom:
           - secretRef:
               name: mysql

    #kubectl get pods -n roboshop (to see pods created under roboshop namespace)

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
     project: roboshop
     tier: database
     component: mysql
spec:
  selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
     project: roboshop
     tier: database
     component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port
