apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: app
    component: user
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  #DEPLOYMENT LABELS
  labels:
    project: roboshop
    tier: app
    component: user
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      tier: app
      component: user
  # This is pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: venkattholeti/user:v1
        envFrom:
        - configMapRef:
            name: user

    #kubectl get pods -n roboshop (to see pods created under roboshop namespace)

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
     project: roboshop
     tier: app
     component: user
spec:
  selector: #HERE SELECTORS ARE LABELS (LABELS ARE SELECTORS,HERE THIS SERVICE WILL DEPEND ON LABLES TO SELECT AND WORK ON WHICH PODS)
     project: roboshop
     tier: app
     component: user
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
